# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :raidvm01 => {
        :box_name => "debian/bookworm64",
        :ip_addr => '10.10.10.2',
	:disks => {
		:sas1 => {
			:dfile => './sas1111.vdi',
			:size => 250,
			:port => 1
		},
		:sas2 => {
                        :dfile => './sas1112.vdi',
                        :size => 250, # Megabytes
			:port => 2
		},
                :sas3 => {
                        :dfile => './sas1113.vdi',
                        :size => 250,
                        :port => 3
                },
                :sas4 => {
                        :dfile => './sas1114.vdi',
                        :size => 250, # Megabytes
                        :port => 4
		},
		:sas5 => {
                        :dfile => './sas1115.vdi',
                        :size => 250, # Megabytes
                        :port => 5
                },
                :sas6 => {
                        :dfile => './sas1116.vdi',
                        :size => 250, # Megabytes
                        :port => 6
                }
	}

		
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "public_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]
                  needsController = false
		  boxconfig[:disks].each do |dname, dconf|
			  unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                                needsController =  true
                          end

		  end
                  if needsController == true
                     vb.customize ["storagectl", :id, "--name", "SAS", "--add", "sas" ]
                     boxconfig[:disks].each do |dname, dconf|
                         vb.customize ['storageattach', :id,  '--storagectl', 'SAS', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                     end
                  end
          end
 	  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
              apt update -y
	      apt upgrade -y
	      apt install -y mdadm smartmontools hdparm gdisk parted
	      bash /vagrant/raid_script.txt
  	  SHELL

      end
  end
end

