# -*- mode: ruby -*-
# vim: set ft=ruby :
disk_controller = 'IDE' # MacOS. This setting is OS dependent. Details https://github.com/hashicorp/vagrant/issues/8105


MACHINES = {
  :zfs => {
        :box_name => "centos/7",
        :box_version => "2004.01",
        :provision => "create_zpool.sh",
    :disks => {
        :sata1 => {
            :dfile => './sata10.vdi',
            :size => 512,
            :port => 1
        },
        :sata2 => {
            :dfile => './sata20.vdi',
            :size => 512, # Megabytes
            :port => 2
        },
        :sata3 => {
            :dfile => './sata30.vdi',
            :size => 512,
            :port => 3
        },
        :sata4 => {
            :dfile => './sata40.vdi',
            :size => 512, 
            :port => 4
        },
        :sata5 => {
            :dfile => './sata50.vdi',
            :size => 512,
            :port => 5
        },
        :sata6 => {
            :dfile => './sata60.vdi',
            :size => 512,
            :port => 6
        },
        :sata7 => {
            :dfile => './sata70.vdi',
            :size => 512, 
            :port => 7
        },
        :sata8 => {
            :dfile => './sata80.vdi',
            :size => 512, 
            :port => 8
        },
        :sata9 => {
            :dfile => './sata90.vdi',
            :size => 512, 
            :port => 9
        },
        :sata10 => {
            :dfile => './sata100.vdi',
            :size => 512, 
            :port => 10
        },
    }
        
  },
}


Vagrant.configure("2") do |config|


  MACHINES.each do |boxname, boxconfig|


      config.vm.define boxname do |box|


        box.vm.box = boxconfig[:box_name]
        box.vm.box_version = boxconfig[:box_version]


        box.vm.host_name = "zfs"


        box.vm.provider :virtualbox do |vb|
              vb.customize ["modifyvm", :id, "--memory", "1024"]
              needsController = false
        boxconfig[:disks].each do |dname, dconf|
              unless File.exist?(dconf[:dfile])
              vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
         needsController =  true
         end
        end
            if needsController == true
                vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                boxconfig[:disks].each do |dname, dconf|
                vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                end
             end
          end
        box.vm.provision "shell", path: boxconfig[:provision]
          


    end
  end
end
