Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "web"
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.hostname = "web"
    
  config.vm.network "private_network", ip: "192.168.56.100"

  #config.vm.provision "shell", path: "provision.sh"
end
